version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=salesync_authentication'
      - 'POSTGRES_PASSWORD=authentication'
      - 'POSTGRES_USER=authentication'
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
    ports:
      - '12345:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.1'
    container_name: 'authentication' # Optional, but good for referencing
    ports:
      - "9090:8080"
    command: 'start-dev'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin