version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=salesync_authentication'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '54327:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.1'
    container_name: 'authentication' # Optional, but good for referencing
    ports:
      - "8080:8080"
    command: 'start-dev'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_FEATURES: token-exchange
      KC_DB_URL: jdbc:postgresql://postgres:5432/salesync_authentication
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin