# Server settings
server:
  port: 8292
  servlet:
    context-path: /api/v1
  
  # Spring application settings
spring:
  application:
    name: record-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


token:
  public-key: ${TOKEN_PUBLIC_KEY}
