spring:
    application:
        name: notification-service
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}