version: '3'
services:
  keycloak:
    build:
        context: keycloak
        dockerfile: Dockerfile
    container_name: 'keycloak'
    ports:
      - "8380:8380"
    command: start dev
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  service-registry:
    build:
      context: service-registry
      dockerfile: Dockerfile
    container_name: 'eureka'
    ports:
      - "8761:8761"
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    container_name: 'gateway'
    ports:
      - "8083:8083"
    env_file: env/api-gateway.env
    depends_on:
      - service-registry
# Implementing
#  notification-service:
  message-queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ standard port
      - "15672:15672"  # RabbitMQ management UI
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: "salesync"
      RABBITMQ_DEFAULT_PASS: "salesync"
  authentication:
    build:
      context: authentication
      dockerfile: Dockerfile
    container_name: 'authentication'
    ports:
      - "8082:8082"
    env_file: env/authentication.env
    depends_on:
      - service-registry
      - keycloak
  record-service:
    build:
      context: record-service
      dockerfile: Dockerfile
    container_name: 'record-service'
    ports:
      - "8292:8292"
    env_file: env/record-service.env
    depends_on:
      - service-registry
      - message-queue
    links:
      - service-registry
  type-service:
    build:
      context: type-service
      dockerfile: Dockerfile
    container_name: 'type-service'
    ports:
      - "5000:5000"
    env_file: env/type-service.env
    depends_on:
      - service-registry
      - message-queue
    links:
      - service-registry