version: '3'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8380:8380"