services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=salesync_record_service'
      - 'POSTGRES_PASSWORD=record_service'
      - 'POSTGRES_USER=record_service'
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data  # Persistent data volume
    ports:
      - '54321:5432'
volumes:
  postgres_data:

