services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=salesync_type_service'
      - 'POSTGRES_PASSWORD=type_service'
      - 'POSTGRES_USER=type_service'
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
# Uncomment the below line to allow Postgres to store data on the host machine even after the container is removed
#      - ./src/main/resources/db/data:/var/lib/postgresql/data
    ports:
      - '54320:5432'
volumes:
  postgres_data:
