# version: '3'

networks:
  elastic:

services:
  elasticsearch:
    image: elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      # - xpack.security.enabled=true
      # - xpack.security.audit.enabled=true
      # - xpack.security.authc.api_key.enabled=true
      # - ELASTIC_PASSWORD=admin
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ports:
      - "9200:9200"
    networks:
      - elastic

  Logstash:
    image: logstash:7.17.20
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./postgresql-42.7.3.jar:/usr/share/logstash/bin/postgresql-42.7.3.jar
    command: logstash -f /usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "9600:9600"
    env_file:
      - path: ./.env
        required: true # default
      - path: ./.local.env
        required: false
    # environment:
    #   LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    #   LOGSTASH_OUTPUT_HOST: ${LOGSTASH_OUTPUT_HOST}
    #   LOGSTASH_OUTPUT_PORT: ${LOGSTASH_OUTPUT_PORT}
    #   LOGSTASH_DB_HOST: ${LOGSTASH_DB_HOST}
    #   LOGSTASH_DB_PORT: ${LOGSTASH_DB_PORT}
    #   LOGSTASH_DB_NAME: ${LOGSTASH_DB_NAME}
    #   LOGSTASH_DB_USER: ${LOGSTASH_DB_USER}
    #   LOGSTASH_DB_PASSWORD: ${LOGSTASH_DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elastic
