version: '3'

services:
  elastic-agent:
    image: elastic/elastic-agent:7.17.21 
    container_name: elastic-agent
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://localhost:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MTU0OTY0NzU1MDE6aXpKT0piY2dTVWUwQWtrb1RxVjl6dw
      - FLEET_SERVER_POLICY_ID=499b5aa7-d214-5b5d-838b-3cd76469844e
      - FLEET_SERVER_INSECURE_HTTP=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=admin
      - FLEET_SERVER_ELASTICSEARCH_INSECURE=true
      - FLEET_URL=http://elastic-agent:8220
      - FLEET_ENROLL=1
      - FLEET_INSECURE=true
    ports:
      - "8220:8220"