version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ standard port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "admin"  # Change to your desired username
      RABBITMQ_DEFAULT_PASS: "admin"  # Change to your desired password
