spring:
  application:
    name: type-service
  datasource:
    url: jdbc:postgresql://localhost:54320/salesync_type_service
    username: type_service
    password: type_service
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 5000
  servlet:
    context-path: /api/v1



