keycloak:
  realm: master
  auth-server-url: ${KEYCLOAK_HOST}
  ssl-required: true
  resource: admin-cli
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username

keycloak-config:
  username: ${KEYCLOAK_ADMIN_USER}
  password: ${KEYCLOAK_ADMIN_PASSWORD}

server:
  servlet:
    context-path: /api/v1
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

main-website:
  address: https://www.salesync.org
mail:
  host: ${MAIL_SERVER_HOST}
  port: ${MAIL_SERVER_PORT}
  from: ${DEFAULT_MAIL_DOMAIN}
  starttls: true
  auth: true
  user: ${MAIL_SERVER_USER}
  password: ${MAIL_SERVER_PASSWORD}

keystore:
  location: ${KEYSTORE_PATH}
  password: ${KEYSTORE_PASSWORD}
  alias: ${KEYSTORE_ALIAS}

jwt:
  expiration:
    ms: 7776000000