name: Authentication Service Build

on:
  push:
    branches:
      - main
      - development
    paths:
      - back-end/authentication/**
  pull_request:
    branches:
      - main
      - development
    paths:
      - back-end/authentication/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        working-directory: back-end/authentication
        run: |
          mvn -B -DKEYCLOAK_HOST=${{secrets.KEYCLOAK_HOST_URL}} -DDB_HOST=${{secrets.AUTH_DB_HOST}} \
            -DDB_PORT=${{secrets.AUTH_DB_PORT}} -DDB_NAME=${{secrets.AUTH_DB_NAME}} \
            -DDB_USER=${{secrets.AUTH_DB_USER}} -DDB_PASSWORD=${{secrets.AUTH_DB_PASSWORD}} \
            -DRABBITMQ_HOST=${{secrets.AUTH_RABBITMQ_HOST}} -DRABBITMQ_PORT=${{secrets.AUTH_RABBITMQ_PORT}} \
            -DRABBITMQ_USER=${{secrets.AUTH_RABBITMQ_USER}} -DRABBITMQ_PASSWORD=${{secrets.AUTH_RABBITMQ_PASSWORD}} \
            package --file pom.xml
