name: Frontend Build

on:
  push:
    branches:
      - main
      - development
    paths:
      - front-end/**
  pull_request:
    branches:
      - main
      - development
    paths:
      - front-end/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Start services with Docker Compose
      working-directory: front-end

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 19.x
    - name: Build
      working-directory: front-end
      run: |
        npm install
        npm run build
