name: Authentication Service Build

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'back-end/type-service/**'
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'back-end/type-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file back-end/type-service/pom.xml
